[package]
name = "var_mc_acc_improved"
version = "0.1.0"
edition = "2021"

[dependencies]
# No specific dependencies for this simple accuracy test

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

