name: Bench Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "17 2 * * *"  

jobs:
  bench-nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'      
          cache: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt 

      - name: Install system deps (clang, make)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang make

      - name: Build all (best effort)
        run: |
          make clean || true
          make build || true

      - name: Run benches (strict, короткие прогоны)
        env:
          REPS: "5"
          WARMUP: "2"
          INNER_REPS: "0"
        run: |
          ./benchmarks/run.sh || true
          ls -la benchmarks/results || true

      - name: Upload results (CSV)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bench-results
          path: |
            benchmarks/results/*.csv
          if-no-files-found: warn

      - name: Upload LATEST.md (сводка, если есть)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bench-latest
          path: benchmarks/results/LATEST.md
          if-no-files-found: ignore