name: Bench Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

jobs:
  bench-nightly:
    runs-on: ubuntu-latest
    env:
      REPS: "5"
      FIB_N: "90"
      SIZE: "100000"
      NBODY_N: "4096"
      NBODY_STEPS: "10"
      NBODY_DT: "0.001"
      GOMAXPROCS: "1"
      CFLAGS_NATIVE: "-O3"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: dtolnay/rust-toolchain@stable
      - name: Install build deps
        run: |
          sudo apt-get update && sudo apt-get install -y clang make
      - name: Build
        run: make clean && make build CFLAGS_NATIVE="$CFLAGS_NATIVE"
      - name: AOT demos
        run: |
          ./.bin/tenge -o .bin/sort_cli_qsort.c benchmarks/src/tenge/sort_qsort_cli.tng
          ./.bin/tenge -o .bin/sort_cli_msort.c benchmarks/src/tenge/sort_msort_cli.tng
          ./.bin/tenge -o .bin/sort_cli_pdq.c   benchmarks/src/tenge/sort_pdq_cli.tng
          ./.bin/tenge -o .bin/sort_cli_radix.c benchmarks/src/tenge/sort_radix_cli.tng
          cc -O3 -Iinternal/aotminic/runtime .bin/sort_cli_qsort.c internal/aotminic/runtime/runtime.c -o .bin/sort_cli_qsort
          cc -O3 -Iinternal/aotminic/runtime .bin/sort_cli_msort.c internal/aotminic/runtime/runtime.c -o .bin/sort_cli_msort
          cc -O3 -Iinternal/aotminic/runtime .bin/sort_cli_pdq.c   internal/aotminic/runtime/runtime.c -o .bin/sort_cli_pdq
          cc -O3 -Iinternal/aotminic/runtime .bin/sort_cli_radix.c internal/aotminic/runtime/runtime.c -o .bin/sort_cli_radix
      - name: Run benches
        run: |
          export REPS FIB_N SIZE NBODY_N NBODY_STEPS NBODY_DT GOMAXPROCS
          bash ./benchmarks/run.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-results-nightly
          path: |
            benchmarks/results/*.csv
            benchmarks/results/LATEST.md
          if-no-files-found: warn
